[theme]
base = "dark"

primaryColor = '#ed3d00' # Um verde EPUFABC
backgroundColor = "#0E1117" # Fundo quase preto (padr√£o Streamlit ou Github Dark)
secondaryBackgroundColor = "#262730" # Fundo da sidebar
textColor = "#FAFAFA"
font = "sans serif"

[client]
showSidebarNavigation = false
